name: Release preparation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  create_draft_release:
    # if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Extract version
        id: get_version
        run: echo "version=v$(echo $(cat package.json) | jq -r .version)" >> $GITHUB_ENV

      - name: Create Tag
        run: | 
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git tag ${{ env.version }}
          git push origin ${{ env.version }}
      
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release create ${{ env.version }} \
            --target staging \
            --title ${{ env.version }} \
            --draft \
            --generate-notes
