name: Run cypress tests

on:
  push: # Trigger the job on every commit
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PORT: 3000
    steps:
      - uses: actions/checkout@v2

    #   - name: Run npm install # if cache not found
    #     run: npm install

    #   - name: Install global dependencies
    #     run: npm install -g ts-node

      - name: Echo MY_SECRET
        run: echo ${{ secrets.MY_SECRET }} | cut -c 1-10

    #   - name: Run hello world
    #     run: ts-node helloWorld.ts
