name: Run cypress tests

on:
  push: 
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2

      - name: Echo stuff
        run: echo ${{ secrets.MY_SECRET }} | cut -c 1
      - name: Echo stuff
        run: echo "${{ secrets.MY_SECRET }}" | cut -c 2-
