name: Run cypress tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PORT: 3000
    steps:
      - uses: actions/checkout@v2

      - name: Run npm install # if cache not found
        run: npm install

      - name: Install global dependencies
        run: npm install -g ts-node

      - name: Run hello world
        run: ts-node helloWorld.ts
