name: Run cypress tests

on:
  push: # Trigger the job on every commit
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: prod # Set the prod environment here
    env:
      PORT: 3000
    steps:
      - uses: actions/checkout@v2

    #   - name: Run npm install # if cache not found
    #     run: npm install

    #   - name: Install global dependencies
    #     run: npm install -g ts-node

      - name: Echo stuff
        run: echo ${{ secrets.MY_SECRET }} | cut -c 1-2
      - name: Echo stuff
        run: echo "${{ secrets.MY_SECRET }}" | cut -c 2-

    #   - name: Run hello world
    #     run: ts-node helloWorld.ts
